### ISSUE TITLE
Is there a reason indexes don't get a refers list in prop e?

### ISSUE THREAD

**Issue by Jamstah** [opencontainers/wg-reference-types#67] opened 2022-07-18 22:43 UTC
Proposal says:
> Extend the Image Manifest with a refers field (existing registries should ignore this per OCI's extensibility requirement)

Why not also oci indexes?

**Comment by sudo-bmitch** [comment] 2022-07-18 23:50
It's possible to create a circular reference with the following:

1. Create manifest "child".
2. Create an index "parent", with the manifest list pointing to child, and the refers pointing to child.

At that point, child will always have a manifest pointing to it, the parent. But the parent will always have a manifest that refers to it, the child.

Those circular references can break GC, or any other tooling that recursively parses the registry.

That said, you can push an artifact that refers to an index. So a multi-platform image can have a signature, SBOM, and other metadata associated with it. And if you need multiple things to refer to a manifest, they can be pushed as multiple artifacts that each individual refer to your manifest.

**Comment by Jamstah** [comment] 2022-07-19 08:52
Can't you have a circular reference anyway just by setting up two images that refer to each other?

I don't see it being special in the index case. The graph of refers has no circular reference protection defined in this proposal.

What is the intended use case of having the refers field in an image index? I'm wondering if the same case would apply to indexes.

**Comment by Jamstah** [comment] 2022-07-19 10:12
> The image manifest only has blobs as child objects, so it is not possible to have a refer, that can only point to a manifest, point to one of those. With that restriction, we avoid the possibility of creating circular dependencies.

I meant have an artifact a that refers to image b, and image b that refers to artifact a.

However, I just realised that actually, because you have to change the digest to add a refers entry, there's no (practical) way to do that.

> The refers field creates that reverse link that we can query via an API. We ask the registry to list all manifests that has a refers field pointing to our manifest. So if you have an image or index manifest, you can query for all of the artifacts (pushed using either the image schema or a proposed artifact schema) that refer to the image (like signatures and SBOMs).

OK, so the bit I was missing here was "using either the image schema or a proposed artifact schema" - I get the intent of the propsal but was assuming that sboms/signatures would use the artifact schema only. I would argue that any reason you have for pointing an image at another image (perhaps you have a debug image with additional binaries or something that would point to the image its supposed to debug? Or a mysql client image that would point at the server image? Are there better examples?), you could have that same reason for pointing an image index at another image (index). If you are also allowing generic artifacts to use the image schema then it makes more sense.

> Is there a use case you have for adding the refers field to the index definition? You would need an artifact that needs to be represented as an index, which I don't believe we've seen yet.

No, I was really just thinking of completeness while considering how I would implement this in the distribution repo. And as I said above, any use case for allowing a singular executable image to refer to a manifest extends to allowing a manifest list to refer to a manfiest.

Personally, I would still say that having a circular reference isn't necessarily a problem. When processing the registry graph I would expect you'd be only interested in edges of a given type (ORAS reference, reference types references, index manifest, etc). If you were looking at the graph as a whole (perhaps GC?) then you'd need to take into account circular references, but typical GC algorithms handle circular references just fine.

**Comment by sudo-bmitch** [comment] 2022-07-20 02:43
> I meant have an artifact a that refers to image b, and image b that refers to artifact a.
> 
> However, I just realised that actually, because you have to change the digest to add a refers entry, there's no (practical) way to do that.

Correct, the model of the DAG prevents cycles by design. We don't want to break that with the introduction of the refers field acting as a reverse pointer.

> OK, so the bit I was missing here was "using either the image schema or a proposed artifact schema" - I get the intent of the propsal but was assuming that sboms/signatures would use the artifact schema only.

Since that manifest is not defined today, the artifact manifest cannot be used with any existing registry until that registry is upgraded. We also expect some registries may never upgrade, so backwards compatible solutions are needed.

> I would argue that any reason you have for pointing an executable image at another manifest (perhaps you have a debug image with additional binaries or something that would point to the image its supposed to debug? Or a mysql client image that would point at the server image? Are there better examples?), you could have that same reason for pointing an image index at another manifest. If you are also allowing generic artifacts to use the image schema then it makes more sense.

I haven't heard this use case before. The expectation for the working group was to attach metadata to an existing image, I don't think creating an arbitrary graph between different executable images is covered by our goals. This use case may be better handled by creating an index of associated images, rather than adding a referrer.

> Personally, I would still say that having a circular reference isn't necessarily a problem. When processing the registry graph I would expect you'd be only interested in edges of a given type (ORAS reference, reference types references, index manifest, etc). If you were looking at the graph as a whole (perhaps GC?) then you'd need to take into account circular references, but typical GC algorithms handle circular references just fine.

There's also recursive image mirroring tools in addition to GC. And others may create a UI to open a tree of objects. The DAG assumption has been baked into enough code that I'm very cautious about the implications of changing that assumption.

**Comment by sudo-bmitch** [comment] 2022-08-01 20:34
Closing this for now, but feel free to follow up here, slack, or in one of our weekly meetings.

**Closed by sudo-bmitch** 2022-08-01 20:34 UTC
